/usr/bin/g++ -std=gnu++20 -fdiagnostics-color=always -g /home/taku/projects/kyopro/library/kypro_tool/random_test/random_tester.cpp -o /home/taku/projects/kyopro/library/kypro_tool/random_test/random_tester -I /home/taku/lib/ac-library-master
In file included from /usr/include/c++/13/bits/uses_allocator_args.h:38,
                 from /usr/include/c++/13/bits/memory_resource.h:41,
                 from /usr/include/c++/13/string:58,
                 from /usr/include/c++/13/bitset:52,
                 from /usr/include/x86_64-linux-gnu/c++/13/bits/stdc++.h:52,
                 from /home/taku/projects/kyopro/library/kypro_tool/random_test/random_tester.cpp:1:
/usr/include/c++/13/tuple: In instantiation of ‘constexpr decltype(auto) std::__apply_impl(_Fn&&, _Tuple&&, index_sequence<_Idx ...>) [with _Fn = operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const int&, const int&, const int&, const vector<tuple<int, int, int>, allocator<tuple<int, int, int> > >&>&; long unsigned int ..._Idx = {0, 1, 2, 3}; index_sequence<_Idx ...> = integer_sequence<long unsigned int, 0, 1, 2, 3>]’:
/usr/include/c++/13/tuple:2313:31:   required from ‘constexpr decltype(auto) std::apply(_Fn&&, _Tuple&&) [with _Fn = operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const int&, const int&, const int&, const vector<tuple<int, int, int>, allocator<tuple<int, int, int> > >&>&]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:8:10:   required from ‘std::ostream& operator<<(std::ostream&, const std::tuple<_UTypes ...>&) [with T = {const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&}; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:57:14:   required from ‘std::ostream& operator<<(std::ostream&, const T&) [with T = TestCase; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/data.hpp:27:13:   required from here
/usr/include/c++/13/tuple:2302:27: error: no matching function for call to ‘__invoke(operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>, const int&, const int&, const int&, const std::vector<std::tuple<int, int, int> >&)’
 2302 |       return std::__invoke(std::forward<_Fn>(__f),
      |              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
 2303 |                            std::get<_Idx>(std::forward<_Tuple>(__t))...);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/13/bits/ranges_algobase.h:39,
                 from /usr/include/c++/13/bits/ranges_algo.h:38,
                 from /usr/include/c++/13/algorithm:63,
                 from /usr/include/x86_64-linux-gnu/c++/13/bits/stdc++.h:51:
/usr/include/c++/13/bits/invoke.h:90:5: note: candidate: ‘template<class _Callable, class ... _Args> constexpr typename std::__invoke_result<_Functor, _ArgTypes>::type std::__invoke(_Callable&&, _Args&& ...)’
   90 |     __invoke(_Callable&& __fn, _Args&&... __args)
      |     ^~~~~~~~
/usr/include/c++/13/bits/invoke.h:90:5: note:   template argument deduction/substitution failed:
/usr/include/c++/13/bits/invoke.h: In substitution of ‘template<class _Callable, class ... _Args> constexpr typename std::__invoke_result<_Functor, _ArgTypes>::type std::__invoke(_Callable&&, _Args&& ...) [with _Callable = operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>; _Args = {const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&}]’:
/usr/include/c++/13/tuple:2302:27:   required from ‘constexpr decltype(auto) std::__apply_impl(_Fn&&, _Tuple&&, index_sequence<_Idx ...>) [with _Fn = operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const int&, const int&, const int&, const vector<tuple<int, int, int>, allocator<tuple<int, int, int> > >&>&; long unsigned int ..._Idx = {0, 1, 2, 3}; index_sequence<_Idx ...> = integer_sequence<long unsigned int, 0, 1, 2, 3>]’
/usr/include/c++/13/tuple:2313:31:   required from ‘constexpr decltype(auto) std::apply(_Fn&&, _Tuple&&) [with _Fn = operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const int&, const int&, const int&, const vector<tuple<int, int, int>, allocator<tuple<int, int, int> > >&>&]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:8:10:   required from ‘std::ostream& operator<<(std::ostream&, const std::tuple<_UTypes ...>&) [with T = {const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&}; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:57:14:   required from ‘std::ostream& operator<<(std::ostream&, const T&) [with T = TestCase; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/data.hpp:27:13:   required from here
/usr/include/c++/13/bits/invoke.h:90:5: error: no type named ‘type’ in ‘struct std::__invoke_result<operator<< <const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>(std::ostream&, const std::tuple<const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>&)::<lambda(const auto:56&& ...)>, const int&, const int&, const int&, const std::vector<std::tuple<int, int, int>, std::allocator<std::tuple<int, int, int> > >&>’
/usr/include/c++/13/tuple: In instantiation of ‘constexpr decltype(auto) std::__apply_impl(_Fn&&, _Tuple&&, index_sequence<_Idx ...>) [with _Fn = operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const vector<int, allocator<int> >&>&; long unsigned int ..._Idx = {0}; index_sequence<_Idx ...> = integer_sequence<long unsigned int, 0>]’:
/usr/include/c++/13/tuple:2313:31:   required from ‘constexpr decltype(auto) std::apply(_Fn&&, _Tuple&&) [with _Fn = operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const vector<int, allocator<int> >&>&]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:8:10:   required from ‘std::ostream& operator<<(std::ostream&, const std::tuple<_UTypes ...>&) [with T = {const std::vector<int, std::allocator<int> >&}; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:57:14:   required from ‘std::ostream& operator<<(std::ostream&, const T&) [with T = Result; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/data.hpp:32:13:   required from here
/usr/include/c++/13/tuple:2302:27: error: no matching function for call to ‘__invoke(operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>, const std::vector<int>&)’
 2302 |       return std::__invoke(std::forward<_Fn>(__f),
      |              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
 2303 |                            std::get<_Idx>(std::forward<_Tuple>(__t))...);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/13/bits/invoke.h:90:5: note: candidate: ‘template<class _Callable, class ... _Args> constexpr typename std::__invoke_result<_Functor, _ArgTypes>::type std::__invoke(_Callable&&, _Args&& ...)’
   90 |     __invoke(_Callable&& __fn, _Args&&... __args)
      |     ^~~~~~~~
/usr/include/c++/13/bits/invoke.h:90:5: note:   template argument deduction/substitution failed:
/usr/include/c++/13/bits/invoke.h: In substitution of ‘template<class _Callable, class ... _Args> constexpr typename std::__invoke_result<_Functor, _ArgTypes>::type std::__invoke(_Callable&&, _Args&& ...) [with _Callable = operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>; _Args = {const std::vector<int, std::allocator<int> >&}]’:
/usr/include/c++/13/tuple:2302:27:   required from ‘constexpr decltype(auto) std::__apply_impl(_Fn&&, _Tuple&&, index_sequence<_Idx ...>) [with _Fn = operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const vector<int, allocator<int> >&>&; long unsigned int ..._Idx = {0}; index_sequence<_Idx ...> = integer_sequence<long unsigned int, 0>]’
/usr/include/c++/13/tuple:2313:31:   required from ‘constexpr decltype(auto) std::apply(_Fn&&, _Tuple&&) [with _Fn = operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>; _Tuple = const tuple<const vector<int, allocator<int> >&>&]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:8:10:   required from ‘std::ostream& operator<<(std::ostream&, const std::tuple<_UTypes ...>&) [with T = {const std::vector<int, std::allocator<int> >&}; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/debug_print.hpp:57:14:   required from ‘std::ostream& operator<<(std::ostream&, const T&) [with T = Result; std::ostream = std::basic_ostream<char>]’
/home/taku/projects/kyopro/library/kypro_tool/random_test/function_file/data.hpp:32:13:   required from here
/usr/include/c++/13/bits/invoke.h:90:5: error: no type named ‘type’ in ‘struct std::__invoke_result<operator<< <const std::vector<int, std::allocator<int> >&>(std::ostream&, const std::tuple<const std::vector<int, std::allocator<int> >&>&)::<lambda(const auto:56&& ...)>, const std::vector<int, std::allocator<int> >&>’