g++ -std=c++17 -I ../../vcpkg/installed/x64-linux/include/ -o snip ./library/kypro_tool/add_snip/main.cpp
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `main':
main.cpp:(.text+0x5227): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x5476): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x59d9): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x5b96): undefined reference to `CLI::Option::expected(int, int)'
/usr/bin/ld: main.cpp:(.text+0x5c54): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x5e11): undefined reference to `CLI::Option::expected(int, int)'
/usr/bin/ld: main.cpp:(.text+0x5ecf): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x5f94): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x612b): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x6394): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: main.cpp:(.text+0x652b): undefined reference to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: /tmp/ccu7jyiD.o:main.cpp:(.text+0x69f0): more undefined references to `CLI::App::add_subcommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)' follow
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `main':
main.cpp:(.text+0x6a53): undefined reference to `CLI::App::parse(int, char const* const*)'
/usr/bin/ld: main.cpp:(.text+0x7b50): undefined reference to `CLI::App::exit(CLI::Error const&, std::ostream&, std::ostream&) const'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `__static_initialization_and_destruction_0()':
main.cpp:(.text+0xab59): undefined reference to `CLI::detail::ExistingFileValidator::ExistingFileValidator()'
/usr/bin/ld: main.cpp:(.text+0xab8b): undefined reference to `CLI::detail::ExistingDirectoryValidator::ExistingDirectoryValidator()'
/usr/bin/ld: main.cpp:(.text+0xabbd): undefined reference to `CLI::detail::ExistingPathValidator::ExistingPathValidator()'
/usr/bin/ld: main.cpp:(.text+0xabef): undefined reference to `CLI::detail::NonexistentPathValidator::NonexistentPathValidator()'
/usr/bin/ld: main.cpp:(.text+0xac21): undefined reference to `CLI::detail::EscapedStringTransformer::EscapedStringTransformer()'
/usr/bin/ld: main.cpp:(.text+0xade2): undefined reference to `CLI::detail::IPV4Validator::IPV4Validator()'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `CLI::App::App(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN3CLI3AppC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_[_ZN3CLI3AppC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_]+0x78): undefined reference to `CLI::App::App(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, CLI::App*)'
/usr/bin/ld: main.cpp:(.text._ZN3CLI3AppC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_[_ZN3CLI3AppC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_]+0xf2): undefined reference to `CLI::App::set_help_flag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `CLI::App::got_subcommand(CLI::App const*) const':
main.cpp:(.text._ZNK3CLI3App14got_subcommandEPKS0_[_ZNK3CLI3App14got_subcommandEPKS0_]+0x23): undefined reference to `CLI::App::get_subcommand(CLI::App const*) const'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `bool CLI::detail::lexical_cast<double, (CLI::detail::enabler)0>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double&)':
main.cpp:(.text._ZN3CLI6detail12lexical_castIdLNS0_7enablerE0EEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERT_[_ZN3CLI6detail12lexical_castIdLNS0_7enablerE0EEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERT_]+0x14a): undefined reference to `CLI::detail::get_group_separators[abi:cxx11]()'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `CLI::Option* CLI::App::add_flag<bool, (CLI::detail::enabler)0>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN3CLI3App8add_flagIbLNS_6detail7enablerE0EEEPNS_6OptionENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERT_SB_[_ZN3CLI3App8add_flagIbLNS_6detail7enablerE0EEEPNS_6OptionENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERT_SB_]+0xd1): undefined reference to `CLI::App::_add_flag_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<bool (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `CLI::Option* CLI::App::add_option<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, (CLI::detail::enabler)0>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN3CLI3App10add_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_LNS_6detail7enablerE0EEEPNS_6OptionES7_RT_S7_[_ZN3CLI3App10add_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_LNS_6detail7enablerE0EEEPNS_6OptionES7_RT_S7_]+0xd9): undefined reference to `CLI::App::add_option(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<bool (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>)'
/usr/bin/ld: main.cpp:(.text._ZN3CLI3App10add_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_LNS_6detail7enablerE0EEEPNS_6OptionES7_RT_S7_[_ZN3CLI3App10add_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_LNS_6detail7enablerE0EEEPNS_6OptionES7_RT_S7_]+0x1b8): undefined reference to `CLI::Option::type_size(int, int)'
/usr/bin/ld: main.cpp:(.text._ZN3CLI3App10add_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_LNS_6detail7enablerE0EEEPNS_6OptionES7_RT_S7_[_ZN3CLI3App10add_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_LNS_6detail7enablerE0EEEPNS_6OptionES7_RT_S7_]+0x1cc): undefined reference to `CLI::Option::expected(int)'
/usr/bin/ld: /tmp/ccu7jyiD.o: in function `CLI::Option* CLI::App::add_option<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, (CLI::detail::enabler)0>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN3CLI3App10add_optionISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EESA_LNS_6detail7enablerE0EEEPNS_6OptionES8_RT_S8_[_ZN3CLI3App10add_optionISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EESA_LNS_6detail7enablerE0EEEPNS_6OptionES8_RT_S8_]+0xd9): undefined reference to `CLI::App::add_option(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<bool (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>)'
/usr/bin/ld: main.cpp:(.text._ZN3CLI3App10add_optionISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EESA_LNS_6detail7enablerE0EEEPNS_6OptionES8_RT_S8_[_ZN3CLI3App10add_optionISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EESA_LNS_6detail7enablerE0EEEPNS_6OptionES8_RT_S8_]+0x186): undefined reference to `CLI::Option::type_size(int, int)'
/usr/bin/ld: main.cpp:(.text._ZN3CLI3App10add_optionISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EESA_LNS_6detail7enablerE0EEEPNS_6OptionES8_RT_S8_[_ZN3CLI3App10add_optionISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EESA_LNS_6detail7enablerE0EEEPNS_6OptionES8_RT_S8_]+0x19a): undefined reference to `CLI::Option::expected(int)'
collect2: error: ld returned 1 exit status